services:
  api-solid-pg:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      POSTGRES_DB: apisolid
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: Senha@123
    volumes:
      - apisolid-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "sa", "-d", "apisolid" ]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s

volumes:
  apisolid-data:
