name: Run E2E Tests

on: [pull_request]

jobs: 
  run-unit-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    services:
       postgres:
        image: postgres:latest
        ports:
          - "5432:5432"
        environment:
          POSTGRES_DB: apisolid
          POSTGRES_USER: sa
          POSTGRES_PASSWORD: Senha@123
        healthcheck:
          test: [ "CMD", "pg_isready", "-U", "sa", "-d", "apisolid" ]
          interval: 30s
          retries: 3
          start_period: 10s
          timeout: 10s

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22.11.0
          cache: 'npm'

      - run: npm ci
      - run: npm run test:e2e
        env:
          JWT_SECRET: testing
          DATABASE_URL: "postgresql://docker:docker@localhost:5432/apisolid?schema=public"
