name: Run E2E Tests

on: [pull_request]

jobs: 
  run-unit-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    services:
       postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: apisolid
          POSTGRES_USER: sa
          POSTGRES_PASSWORD: Senha@123
        options: >-
          --health-cmd="pg_isready -U sa"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22.11.0
          cache: 'npm'

      - run: npm ci
      - run: npm run test:e2e
        env:
          env:
            JWT_SECRET: testing
            DATABASE_URL: "postgresql://sa:Senha@123@localhost:5432/apisolid?schema=public"
